---
- name: Update and Upgrade VPN Server
  hosts: vpn_server
  become: yes

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Cache valid for 1 hour (optional)

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist 

    - name: Install OpenVPN
      ansible.builtin.apt:
        name: openvpn
        state: present
        update_cache: yes 